---
title: "J1798 PDAC trial - mIHC visualization"
author: "Ludmila Danilova"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message = FALSE,
                      warning = FALSE)
rm(list = ls())

library(dplyr)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(data.table)
library("DT")
library(gridExtra)
library(pals)
library(kableExtra)

# set root folder
rootDir = "../"

# load shared parameters and functions
source(paste0(rootDir,"parameters_and_functions.r"))

#=========================
# read in sample annotation and mapping
patTab = read.csv(file = paste0(rootDir,"input_data/table_patients.csv"), row.names = 1)
# switch to R/NR annotation
patTab = patTab %>% mutate(RECIST = factor(RECIST,levels = c("Responder", "NonResponder"), labels = c("R","NR")))


```
Create figures for mIHC data. Preprocessing and preliminary analysis were done by Courtney B. Betts

# Cell densities

```{r echo=FALSE}
#=============================
# read in densities
dens = read.csv(file = paste0(rootDir,"input_data/table_mIHC_cell_densities.csv"), row.names = 1)

cellTypes = rownames(dens)

# transpose, extract time point and add response
dens = t(dens)
dens = data.frame(
  patientID = paste(sapply(strsplit(rownames(dens), '_'), geti,1), sapply(strsplit(rownames(dens), '_'), geti,2), sep = '_'),
  timepoint = sapply(strsplit(rownames(dens), '_'), geti,3), 
  dens, check.names = F)

# add response
dens = dens %>% mutate(RECIST = patTab[patientID,"RECIST"])
table(dens$timepoint)

# exclude PD from the analysis
dens = dens %>% filter(timepoint != "PD")

# find pairs
mat = printPairs(dens)

```

## Bar plot

```{r echo=FALSE}
# define cell types to plot
immuneCells = colnames(dens)[c(7:9,11:12,16:17,20:21)]
immuneCells_labels = data.frame( 
                     levels = c("Immune other","Myeloid other","CD66b", "Total DCs","total monocytes","total macrophages", "CD20", "CD3+CD8- (putative CD4)", "CD3+CD8+"), 
                     labels = c("Immune other","Myeloid other","Granulocytes", "Total DCs","Total monocytes","Total macrophages", "CD20+ B cells", "CD4+ T cells", "CD8+ T cells"))
rownames(immuneCells_labels) = immuneCells_labels$levels

macrophages = c("CD163- macrophages", "CD163+ macrophages")


# cluster colors
clustercolors <- toupper(as.character(c(cols25(n=25),alphabet(n=19)))[1:length(immuneCells)])
names(clustercolors) <- levels(immuneCells)
# make barplot with average by time point
# immune cells
d = dens %>% filter(timepoint != "C2D1") 
avg = aggregate(d %>% select(immuneCells),by = list(d$timepoint), FUN = mean)

colnames(avg)[1] = "timepoint"
df_melt = melt(avg, id.vars ="timepoint", measure.vars = immuneCells)

print(ggplot(df_melt, aes(fill=factor(variable, levels = immuneCells_labels$levels, labels = immuneCells_labels$labels), y=as.numeric(value), x=timepoint)) + 
    geom_bar(position="stack", stat="identity")+
      scale_fill_manual("Cell type", values=clustercolors)+
      ylab("Cell densities") + xlab("Time point"))

# macrophages 
d = dens %>% filter(timepoint != "C2D1") 
avg = aggregate(d %>% select(macrophages),by = list(d$timepoint), FUN = mean)

colnames(avg)[1] = "timepoint"
df_melt = melt(avg, id.vars ="timepoint", measure.vars = macrophages)

print(ggplot(df_melt, aes(fill=variable, y=as.numeric(value), x=timepoint)) + 
    geom_bar(position="stack", stat="identity")+
      scale_fill_manual("Cell type", values=clustercolors)+
      ylab("Cell densities") + xlab("Time point"))

```

## Table

P-values from paired two-sided Wilcoxon test between time points and mean of difference between time points

```{r table, echo=FALSE}
# paired Wilcoxon
res = t(sapply(as.character(cellTypes), pairedWilcox, dens))

res = round(res,3)
write.csv(cbind(cluster = rownames(res),res), row.names = F, file = paste0(rootDir,"output_data/table_mIHC_wilcox_pvalues_densities.csv"))

datatable(res)
# significant proportions
sigProp = apply(res[,grep("pValue",colnames(res))],2,function(x) names(x)[which(x < pVal)])

print("Significant change (p-value < 0.05) in proportions of cells in the following cell types:")
print(sigProp)

```
## Boxplots

### Macrophages

```{r boxplots_macropahge, echo=FALSE, fig.width= 4, fig.height= 3 }

for(i in macrophages)
{
  df = cbind(cell = dens[,i], dens[,c("patientID", "timepoint", "RECIST") ] )
#print(i)
    p1 = ggpaired(df, x="timepoint",y="cell", id = "patientID", line.size = .7, line.color = "RECIST",palette =  recistCol,
     title = i, xlab="Time point", ylab = "Cell proportions") +
       theme(legend.position="right") +
      scale_x_discrete(labels=timeLab)
 
     # two time points
    df = df %>% filter(timepoint != "C2D1")  

    p2 = ggpaired(df, x="timepoint",y="cell", id = "patientID", line.size = .7, line.color = "RECIST",palette =  recistCol,
     title = i, xlab="Time point", ylab = "Cell proportions") +
       theme(legend.position="right") +
      scale_x_discrete(labels=timeLab)

   print(p1)
   print(p2) 
}


```

# Ratios

```{r ratios, echo=FALSE, fig.width= 4, fig.height= 3 }
#===============
# read in pre-calculated ratios (from OHSU)
r = read.csv(file = paste0(rootDir,"input_data/table_mIHC_ratios.csv"), row.names = 1)

ratios = rownames(r)

# transpose, extract time point and add response
r = t(r)
r = data.frame(
  patientID = paste(sapply(strsplit(rownames(r), '_'), geti,1), sapply(strsplit(rownames(r), '_'), geti,2), sep = '_'),
  timepoint = sapply(strsplit(rownames(r), '_'), geti,3), 
  r, check.names = F)

# add response
r = r %>% mutate(RECIST = patTab[patientID,"RECIST"])
table(r$timepoint)

# exclude PD from the analysis
r = r %>% filter(timepoint != "PD")

res = t(sapply(as.character(ratios), pairedWilcox, r))

res = round(res,3)

kable(res, "simple")

for(i in ratios)
{
df = cbind(ratio = r[,i], r[,c("patientID", "timepoint", "RECIST") ] )
#print(i)
     # two time points
    df = df %>% filter(timepoint != "C2D1")  

    p = ggpaired(df, x="timepoint",y="ratio", id = "patientID", line.size = .7, line.color = "RECIST",palette =  recistCol,
     title = "", xlab="Time point", ylab = i) +
       theme(legend.position="right") +
#  stat_compare_means()+
      scale_x_discrete(labels=timeLab)
    
    print(p)
}
```

# Percentage 
of cell expressing a functional marker in a specific cell type

## Table

```{r, echo=FALSE, fig.width= 4, fig.height= 3 }
#=============================
# read in percentages
perc = read.csv(file = paste0(rootDir,"input_data/table_mIHC_percentages.csv"))

markers = paste(perc$marker,perc$cell_type, sep = " in ")
rownames(perc) = markers

# transpose, extract time point and add response
perc = t(perc)
perc = data.frame(
  patientID = paste(sapply(strsplit(rownames(perc), '_'), geti,1), sapply(strsplit(rownames(perc), '_'), geti,2), sep = '_'),
  timepoint = sapply(strsplit(rownames(perc), '_'), geti,3), 
  perc, check.names = F)

# add response
perc = perc %>% mutate(RECIST = patTab[patientID,"RECIST"])
table(perc$timepoint)

# exclude PD from the analysis
perc = perc %>% filter(timepoint != "PD")


# paired Wilcoxon
res = t(sapply(markers, pairedWilcox, perc))

res = round(res,3)
 write.csv(cbind(cluster = rownames(res),res), row.names = F, file = paste0(rootDir,"output_data/table_mIHC_wilcox_pvalues_percentage.csv"))
 
datatable(res)

# significant percentages
sigProp = apply(res[,grep("pValue",colnames(res))],2,function(x) names(x)[which(x < pVal)])

print("Significant change (p-value < 0.05) in the following cell types:")
print(sigProp)


```

## Boxplots

```{r, echo=FALSE, fig.width= 4, fig.height= 3 }

for(i in unlist(sigProp))
{
df = cbind(percent = as.numeric(perc[,i]), perc[,c("patientID", "timepoint", "RECIST") ] )
#print(i)
     # two time points
    df = df %>% filter(timepoint != "C2D1")  

    p = ggpaired(df, x="timepoint",y="percent", id = "patientID", line.size = .7, line.color = "RECIST",palette =  recistCol,
     title = "", xlab="Time point", ylab = i) +
       theme(legend.position="right") +
#  stat_compare_means()+
      scale_x_discrete(labels=timeLab)
    
    print(p)
}

```

```{r echo=FALSE}
sessionInfo()
```




